version: '3'
services:
    # Laravel Application Service Polling_app
    polling_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_polling_app
        working_dir: /var/www
        volumes:
            - .api-polling:/var/www
            - vendor:/var/www/vendor
        ports:
          - "8001:80"
        networks:
            - laravel

    # Laravel Application Service SSE_app
    sse_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_sse_app
        working_dir: /var/www
        volumes:
            - .server-sent-events:/var/www
            - vendor:/var/www/vendor
        ports:
          - "8002:80"
        networks:
            - laravel
            
    # Laravel Application Service WS_app
    ws_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_ws_app
        working_dir: /var/www
        volumes:
            - .web-sockets:/var/www
            - vendor:/var/www/vendor
        ports:
          - "8003:80"
        networks:
            - laravel

    # MySQL Service
    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel  # Make sure this matches DB_DATABASE in your .env file
            MYSQL_USER: sail  # Make sure this matches DB_USERNAME in your .env file
            MYSQL_PASSWORD: password  # Make sure this matches DB_PASSWORD in your .env file
        volumes:
            - sailmysql:/var/lib/mysql
        networks:
            - laravel

    # PHPMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - laravel

networks:

    laravel:
        driver: bridge

volumes:
    vendor:
        driver: local
    sailmysql:
        driver: local
